name: Deploying to Production (Google Cloud Platform VM)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - development
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'master')
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Setting up NodeJS Environment
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Deploy to Google Cloud Platform VM (Production)
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        VM_USERNAME: ${{ secrets.VM_USERNAME }}
        VM_IP: ${{ secrets.VM_IP }}
      run: |
        echo "$SSH_PRIVATE_KEY" > key.pem
        chmod 600 key.pem

        # Sync project files to the server
        rsync -avz -e "ssh -i key.pem -o StrictHostKeyChecking=no" --delete . $VM_USERNAME@$VM_IP:/var/www/website-portfolio/

        # Execute commands on the server
        ssh -i key.pem -o StrictHostKeyChecking=no $VM_USERNAME@$VM_IP << EOF
          cd /var/www/website-portfolio

          # Install modules dependencies
          npm install

          # Build the project
          npm run build

          # Check if PM2 is installed and install it if not
          if ! command -v pm2 &> /dev/null
          then
              echo "PM2 not found, installing..."
              sudo npm install -g pm2
          else
              echo "PM2 is already installed"
          fi

          # Delete existing PM2 process if it exists
          if pm2 list | grep -q "website-portfolio"
          then
              echo "Deleting existing PM2 process..."
              pm2 delete website-portfolio
          else
              echo "PM2 process not found"
          fi

          # Start the Next.js application with PM2
          pm2 start npm --name "website-portfolio" -- start || true

          # Save the PM2 process list
          pm2 save
        EOF
      shell: bash
